# SPDX-License-Identifier: BSD-3-Clause
- name: Define default provider as nm
  set_fact:
    network_provider_default: nm

- name: Override default provider to initscipts for older systems
  set_fact:
    network_provider_default: initscripts
  when:
    - ansible_distribution_major_version == "6"
    - ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

# needed for ansible_facst.packages
- name: Check which packages are installed
  package_facts:

# Depending on the plugins, checking installed packages might be slow
# for example subscription manager might slow this down
# Therefore install packages only when rpm does not find them
- name: Install packages
  package:
      name: "{{ network_packages }}"
      state: present
#  when:
#    - not network_packages is subset(ansible_facts.packages.keys())

- name: Enable network service
  service:
      name: "{{ network_service_name }}"
      state: started
      enabled: yes

- name: Configure networking connection profiles
  network_connections:
      provider:            "{{ network_provider           | mandatory }}"
      ignore_errors:       "{{ network_ignore_errors      | default(omit) }}"
      force_state_change:  "{{ network_force_state_change | default(omit) }}"
      connections:         "{{ network_connections        | default([]) }}"

- name: Re-test connectivity
  ping:
